apiVersion: v1
kind: Pod

metadata:
  name: fastapi-task-pod
  labels:
    app: patient-api

spec:
  containers:
    - name: fastapi-task-container
      image: fastapi_task:latest
      
      ports:
        - containerPort: 8000